services:

  mysql-db:
    image: blagoja95/job-board-mysql-image:v1.0.1
    container_name: job-board-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - job-board-net
    profiles:
      - 'php'
      - 'jv'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_my_admin
    links:
      - mysql-db
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - ${PMA_PORT}:80
    networks:
      - job-board-net
    profiles:
      - 'php'
      - 'jv'

  tomcat:
    image: blagoja95/job-board-tomcat-image:v1.2.0
    container_name: job-board-be
    networks:
      - job-board-net
    ports:
      - ${TCAT_PORT}:${TCAT_PORT}
    expose:
      - ${TCAT_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    profiles:
      - 'jv'

  apache:
    build:
      context: .
      dockerfile: ./docker/apache/Apache.Dockerfile
    container_name: apache_bck
    volumes:
      - ./backend/pbck/src:/var/www/html/
    networks:
      - job-board-net
    ports:
      - ${APACHE_PORT}:${APACHE_PORT}
    expose:
      - ${APACHE_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    profiles:
      - 'php'
      - 'test'

  node-react:
    image: blagoja95/job-board-node-image:v1.2.0
    container_name: job-board-fe
    networks:
      - job-board-net
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    profiles:
      - 'php'
      - 'jv'

networks:
  job-board-net: { }

volumes:
  mysql: