version: "3"

services:

  mysql-db:
    image: blagoja95/job-board-mysql-image:v1.0.1
    container_name: job-board-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_PASSWORD: "mydbpassword"
      MYSQL_ROOT_PASSWORD: "mydbpassword"
      MYSQL_DATABASE: "jobPostingsDB"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - job-board-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_my_admin
    links:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8081:80
    networks:
      - job-board-net

  tomcat:
    image: blagoja95/job-board-tomcat-image:v1.2.0
    container_name: job-board-be
    networks:
      - job-board-net
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  node-react:
    image: blagoja95/job-board-node-image:v1.2.0
    container_name: job-board-fe
    networks:
      - job-board-net
    ports:
      - 3000:3000
    restart: always
    deploy:
      mode: replicated
      replicas: 1

networks:
  job-board-net: { }

volumes:
  mysql: